[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Set environment variables for development mode
[dev]
  command = "npm run dev"
  framework = "sveltekit"
  targetPort = 5173
  port = 8888
  
/*    /index.html   200